atomi/nix-init:
  active: true
  history:
    - version: 13
      time: 2025-09-20T04:17:58.544143Z
      answers:
        init-type:
          type: String
          value: CyanPrint Bun
      deterministic_states: {}
atomi/cyan:
  active: true
  history:
    - version: 10
      time: 2025-09-20T07:30:12.000340Z
      answers:
        atomi-cyan/template-name:
          type: String
          value: workspace
        atomi-cyan/platform:
          type: String
          value: ketone
        atomi-cyan/service:
          type: String
          value: workspace
        atomi-cyan/template-description:
          type: String
          value: CyanPrint Template to initialize new CyanPrint workspace, which includes default CI, gitignore, scripts and sg configurations
      deterministic_states: {}
cyan/new:
  active: true
  history:
    - version: 12
      time: 2025-09-20T04:16:50.929573Z
      answers:
        cyan/new/name:
          type: String
          value: workspace
        cyan/new/more-tags/0:
          type: String
          value: yes
        cyan/new/description:
          type: String
          value: CyanPrint Template to initialize new CyanPrint workspace, which includes default CI, gitignore, scripts and sg configurations
        cyan/new/processor/0:
          type: String
          value: cyan/default
        cyan/new/tag/0:
          type: String
          value: atomi
        cyan/new/username:
          type: String
          value: atomi
        cyan/new/create:
          type: String
          value: Template
        cyan/new/more-tags/1:
          type: String
          value: no
        cyan/new/more-processors/1:
          type: String
          value: no
        cyan/new/source:
          type: String
          value: https://github.com/AtomiCloud/ketone.workspace.git
        cyan/new/more-plugins/0:
          type: String
          value: no
        cyan/new/more-processors/0:
          type: String
          value: yes
        cyan/new/language:
          type: String
          value: Typescript
        cyan/new/project:
          type: String
          value: https://github.com/AtomiCloud/ketone.workspace
        cyan/new/email:
          type: String
          value: admin@atomi.cloud
      deterministic_states: {}
atomi/workspace:
  active: true
  history:
    - version: 20
      time: 2025-09-20T04:18:17.086559Z
      answers:
        atomi/workspace/runtime:
          type: String
          value: Bun
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/enable-docker:
          type: Bool
          value: true
        atomi/workspace/platform:
          type: String
          value: ketone
        atomi/workspace/service:
          type: String
          value: workspace
        atomi/workspace/enable-helm:
          type: Bool
          value: false
      deterministic_states: {}
