name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: let___platform___
      atomi_service: let___service___
  # <%= if (docker) { %>
  docker:
    name: Build Docker
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      atomi_platform: let___platform___
      atomi_service: let___service___

      dockerfile: ./infra/Dockerfile
      image_name: api
  # <%= } %>
  # <%= if (helm) { %>
  helm:
    name: Helm Chart
    uses: ./.github/workflows/⚡reusable-helm.yaml
    secrets: inherit
    with:
      atomi_platform: let___platform___
      atomi_service: let___service___
      chart_path: ./infra/root_chart
  # <%= } %>
