version: '3'

tasks:
  setup:
    desc: 'Setup the repository'
    cmds: <%= if (runtime == "go") { %>
      - go mod tidy
      <%= } else if (runtime == "dotnet") { %>
      - dotnet restore
      <%= } else if (runtime == "bun") { %>
      - bun install
      <%= } %>
      <%= if (secret) { %>
      - ./scripts/local/secrets.sh
      <%= } %>
  deadcode:
    desc: 'Find code only used by tests or not used at all (requires verification)'
    cmds: <%= if (runtime == "go") { %>
      - deadcode ./...
      - <%= } else if (runtime == "dotnet") { %>
      - dn-inspect --projects ./App --projects ./Domain --filter Unused --no-build
      - <%= } else if (runtime == "bun") { %>
      - bun knip --include classMembers,types
      - <%= } %>
