version: '3'

tasks:
  setup:
    desc: 'Setup the repository'
    cmds: <%= if (runtime == "go") { %>
      - go mod tidy
      <%= } else if (runtime == "dotnet") { %>
      - dotnet restore
      <%= } else if (runtime == "bun") { %>
      - bun install
      <%= } %>
      - ./scripts/local/secrets.sh
